### ISSUE TITLE
Get warnings on static pages

### ISSUE THREAD

**Issue by GeorgyKhairov** [moodle-an-hochschulen/moodle-local_staticpage#66]
Hi, 
I got warnings when read static pages

Warning: DOMDocument::loadHTML(): htmlParseStartTag: misplaced <head> tag in Entity, line: 3 in /var/www/[moodle-site]/moodle/local/staticpage/view.php on line 83

Warning: DOMDocument::loadHTML(): htmlParseStartTag: misplaced <body> tag in Entity, line: 6 in /var/www/[moodle-site]/moodle/local/staticpage/view.php on line 83

Fix this bug please.

Plugin version is
v4.0-r1 2022071200

**Comment by GeorgyKhairov** [comment]
![static](https://user-images.githubusercontent.com/91803785/209451464-f454f096-3c0d-4bf4-8e95-f7c3d2d04c11.PNG)

**Comment by abias** [comment]
Hi @GeorgyKhairov ,

this is a HTML parser warning and not necessarily a bug in the plugin. Please make sure that your HTML file is 100% valid (use https://validator.w3.org/ if you are unsure). If your HTML file is valid and the plugin still shows these parser warnings, then please submit the HTML file here and we can try to have a look.

Cheers,
Alex

**Comment by nukuaes** [comment]
Hi, i goy this warning:
`DOMDocument::loadHTML(): Tag svg invalid in Entity, line: 6 in /home/xxx/www/local/staticpage/view.php on line 83PHP message: PHP Warning:  DOMDocument::loadHTML(): Tag path invalid in Entity, line: 7 in /home/xxx/www/local/staticpage/view.php on line 83PHP message: PHP Warning:  DOMDocument::loadHTML(): Tag svg invalid in Entity, line: 11 in /home/xxx/www/local/staticpage/view.php on line 83PHP message: PHP Warning:  DOMDocument::loadHTML(): Tag path invalid in Entity, line: 12 in /home/xxx/www/local/staticpage/view.php on line 83PHP message: PHP Warning:  DOMDocument::loadHTML(): Tag svg invalid in Entity, line: 17 in /home/xxx/www/local/staticpage/view.php on line 83PHP message: PHP Warning:  DOMDocument::loadHTML(): Tag path invalid in Entity, line: 18 in /home/xxx/www/local/staticpage/view.php on line 83PHP message: PHP Warning:  DOMDocument::loadHTML(): Tag svg invalid in Entity, line: 22 in /home/xxx/www/local/staticpage/view.php on line 83PHP message: PHP Warning:  DOMDocument::loadHTML(): Tag path invalid in Entity, line: 23 in /home/xxx/www/local/staticpage/view.php on line 83PHP message: PHP Warning:  DOMDocument::loadHTML(): Tag svg invalid in Entity, line: 28 in /home/xxx/www/local/staticpage/view.php on line 83PHP message: PHP Warning:  DOMDocument::loadHTML(): Tag path invalid in Entity, line: 29 in /home/xxx/www/local/staticpage/view.php on line 83PHP message: PHP Warning:  DOMDocument::loadHTML(): Tag svg invalid in Entity, line: 33 in /home/xxx/www/local/staticpage/view.php on line 83PHP message: PHP Warning:  DOMDocument::loadHTML(): Tag path invalid in Entity, line: 34 in /home/xxx/www/local/staticpage/view.php on line 83'`

**Comment by nukuaes** [comment]
Hi, i goy this warning:
`DOMDocument::loadHTML(): Tag svg invalid in Entity, line: 6 in /home/xxx/www/local/staticpage/view.php on line 83PHP message: PHP Warning:  DOMDocument::loadHTML(): Tag path invalid in Entity, line: 7 in /home/xxx/www/local/staticpage/view.php on line 83PHP message: PHP Warning:  DOMDocument::loadHTML(): Tag svg invalid in Entity, line: 11 in /home/xxx/www/local/staticpage/view.php on line 83PHP message: PHP Warning:  DOMDocument::loadHTML(): Tag path invalid in Entity, line: 12 in /home/x/www/local/staticpage/view.php on line 83PHP message: PHP Warning:  DOMDocument::loadHTML(): Tag svg invalid in Entity, line: 17 in /home/acceso25/www/local/staticpage/view.php on line 83PHP message: PHP Warning:  DOMDocument::loadHTML(): Tag path invalid in Entity, line: 18 in /home/acceso25/www/local/staticpage/view.php on line 83PHP message: PHP Warning:  DOMDocument::loadHTML(): Tag svg invalid in Entity, line: 22 in /home/acceso25/www/local/staticpage/view.php on line 83PHP message: PHP Warning:  DOMDocument::loadHTML(): Tag path invalid in Entity, line: 23 in /home/acceso25/www/local/staticpage/view.php on line 83PHP message: PHP Warning:  DOMDocument::loadHTML(): Tag svg invalid in Entity, line: 28 in /home/acceso25/www/local/staticpage/view.php on line 83PHP message: PHP Warning:  DOMDocument::loadHTML(): Tag path invalid in Entity, line: 29 in /home/acceso25/www/local/staticpage/view.php on line 83PHP message: PHP Warning:  DOMDocument::loadHTML(): Tag svg invalid in Entity, line: 33 in /home/acceso25/www/local/staticpage/view.php on line 83PHP message: PHP Warning:  DOMDocument::loadHTML(): Tag path invalid in Entity, line: 34 in /home/acceso25/www/local/staticpage/view.php on line 83'`

**Comment by christianwolters** [comment]
Hi @nukuaes,

as Alex explained above, these warning may be caused by your HTML file.

Please:

- use https://validator.w3.org/  to check your HTML file
- if the validator says it is valid and your warning is still there:
  - [please open a new issue](https://github.com/moodle-an-hochschulen/moodle-local_staticpage/issues/new/choose)
  - and attach your HTML file to the new issue
  
Cheers
Christian

**Comment by nukuaes** [comment]
Hi, sorry for my delay, the w3 validator says don´t have error
attach scrensoth
![image](https://user-images.githubusercontent.com/21314041/234103238-db8b89f8-030d-4373-ac44-181098af3433.png)
and this is de html code
`<!DOCTYPE html><html class="text-center" lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no"><title>Promoción pack de tutorías de Mar Campos</title><meta name="description" content= "Los usuarios de acceso25 tenéis una promo para las tutorías de Mar Campos, ¡puedes beneficiarte de un 10% de descuento o una grabación gratuita."><meta name="robots" content= "index, follow"></head><META NAME="KEYWORDS" CONTENT="aprobar en la uned,test curso acceso mayores de 25 y 45 años,tes de lengua resueltos 2020-2021-2022,test de inglés uned"><link rel="stylesheet" href="local/staticpage/staticpages/assets/bootstrap/css/bootstrap.min.css?h=3f30c2c47d7d23c7a994db0c862d45a5"></head><body><div class="container d-inline-flex"><img class="img-fluid" src="/local/staticpage/staticpages/img/pack%20de%205%20clases.webp?h=29d7bacb409e67aabdcfce1b6726b7c9" loading="auto" width="1080" height="1080" /></div><script src="local/staticpage/staticpages/assets/bootstrap/js/bootstrap.min.js?h=79ff9637b74326c362fb6f7f5801a7ba"></script></body></html>`
