### ISSUE TITLE
Can not name files with other languages

### ISSUE THREAD

**Issue by javalle** [moodle-an-hochschulen/moodle-local_staticpage#67]
I cannot use filenames with accented Spanish letters. Is there a future version for filenames in other languages?

**Comment by abias** [comment]
Hi @javalle ,

thank you for reporting this issue.
I can understand your need, however we do not plan to add official support of filenames / pagenames with non-ascii letters. We just stick to the best practices of using ascii letters only in filenames and URLs.

Cheers,
Alex
