### ISSUE TITLE
Encoding of non-english characters

### ISSUE THREAD

**Issue by nise** [moodle-an-hochschulen/moodle-local_staticpage#72]
If I upload a HTML file that is encoded in UTF-8 and whose HTML header contains a respective meta tag the text will not be displayed in the right encoding.

<META HTTP-EQUIV="content-type" CONTENT="text/html; charset=utf-8">

**Comment by abias** [comment]
Hi @nise ,

thanks for your issue.
It would be awesome if you could provide an example HTML file so that it can be examined and hopefully a fix can be made.

Cheers,
Alex
