### ISSUE TITLE
Moodle 4.4 compatibility

### ISSUE THREAD

**Issue by renne** [moodle-an-hochschulen/moodle-local_staticpage#73]
According to https://moodle.org/plugins/local_staticpage/versions this plugin is compatible up to Moodle 4.3.
Please add Moodle 4.4 support.

**Comment by vsalgadinho** [comment]
Yes, please! That would be amazing!

**Comment by abias** [comment]
Hi all, 
a Moodle 4.4 release has been published recently.

Cheers,
Alex
